### ISSUE TITLE
Github extension stopped working

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/semantic-mediawiki.org#31] opened 2017-06-11 10:52 UTC
The display of content used to work:

- https://www.semantic-mediawiki.org/wiki/Help:Integration_tests
- https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.5.2

**Comment by JeroenDeDauw** [comment] 2017-06-11 11:50
Meh, so the upgrade done yesterday broke ... something. All tests are passing and I do not have a fully MediaWiki environment to try the extension on, so I can't really check

**Comment by JeroenDeDauw** [comment] 2017-06-11 11:55
@mwjames if you could have a look on your own environment for error/log output that'd be much appreciated. It needs to have PHP 7 or later to work tho

**Comment by mwjames** [comment] 2017-06-11 12:40
> It needs to have PHP 7 or later to work tho

Seems to work locally!

**Comment by kghbln** [comment] 2017-06-11 19:23
@JeroenDeDauw The extension fails silently. So I upgraded the extension and added the following:

Before
```php
$egGitHubDefaultRepo = 'SemanticMediaWiki/SemanticMediaWiki';
```
After
```php
$egGitHubDefaultRepo = 'SemanticMediaWiki/SemanticMediaWiki';
$egGitHubRepositoryWhitelist = [
        'JeroenDeDauw/GitHub',
        'JeroenDeDauw/Maps',
        'JeroenDeDauw/ParserHooks',
        'JeroenDeDauw/Validator',
        'SemanticMediaWiki/SemanticBreadcrumbLinks',
        'SemanticMediaWiki/SemanticCite',
        'SemanticMediaWiki/SemanticCompoundQueries',
        'SemanticMediaWiki/SemanticExternalQueryLookup',
        'SemanticMediaWiki/SemanticExtraSpecialProperties',
        'SemanticMediaWiki/SemanticFormsSelect',
        'SemanticMediaWiki/SemanticGlossary',
        'SemanticMediaWiki/SemanticInterlanguageLinks',
        'SemanticMediaWiki/SemanticMediaWiki',
        'SemanticMediaWiki/SemanticMetaTags',
        'SemanticMediaWiki/SemanticNotifications',
        'SemanticMediaWiki/SemanticResultFormats',
        'SemanticMediaWiki/SemanticScribunto',
        'SemanticMediaWiki/SemanticSignup',
        'SemanticMediaWiki/SemanticWatchlist',
        'SemanticMediaWiki/SummaryCards',
        'SemanticMediaWiki/WhatsNearby'
        ];
$egGitHubCacheTime = 1200;
$egGitHubFetcher = 'mediawiki';
```
I cannot tell if it failed because of the changed configuration, but changing it back does not yield a changed result.

Along the way I shortly had the following error:

```
Warning: Directory /../w/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /../w/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 292
```
The warning does not have practical sense since it does not tell which directory to chmod. I expect that the stuff to be cached ends up in the directory defined by `$wgCacheDirectory`, no?

**Comment by kghbln** [comment] 2017-06-11 19:25
So basically. If I know the directory in question I could ... ;) Still the cache directory is preferred.

**Comment by JeroenDeDauw** [comment] 2017-06-12 04:40
I think you need to make `w/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache` and subdirectories writeable based on that error message... That is retarded though. I will have a look at disabling that cache in the GitHub extension... did not even know it was there

**Comment by kghbln** [comment] 2017-06-12 08:38
> I think you need to make w/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache and subdirectories writeable based on that error message...

This did not help. Now reverted back to version 1.2.0 which did not help. Note neither Apache nor MediaWiki are logging errors. This is utmost odd.

**Comment by JeroenDeDauw** [comment] 2017-06-12 09:07
I will try to make a new release that logs more shit soon

**Comment by kghbln** [comment] 2017-06-14 15:02
@JeroenDeDauw What really puzzles me is that these files are even a no-show after downgrading to previously working versions.

Bunny is sad and grumpy. :(
![sadbunny](https://user-images.githubusercontent.com/1104078/27139396-3885e0c2-5123-11e7-89cb-9ddecef0db2b.jpg)

**Comment by JeroenDeDauw** [comment] 2017-06-14 15:17
Perhaps the cache is misbehaving...

Try turning this method https://github.com/JeroenDeDauw/GitHub/blob/master/src/Setup.php#L98 into

```php
public function newFileFetcher(): FileFetcher {
    return $this->gitHubFetcher === 'mediawiki' ? new MediaWikiFileFetcher() : new SimpleFileFetcher();
}
```

That will completely disable any caching.

**Comment by kghbln** [comment] 2017-06-14 16:47
@JeroenDeDauw You know what I just discovered: GitHub installs to `/vendor/jeroen/mediawiki-github` instead of the expected `/extensions/GitHub`. This may be part of the issue.

**Comment by kghbln** [comment] 2017-06-14 16:50
> Perhaps the cache is misbehaving...

So this is not helping either. Moreover stopping and starting the memcached cache server did not help.

**Comment by JeroenDeDauw** [comment] 2017-06-14 17:22
WTF... not sure how no one noticed that before :D Should be fixed by https://github.com/JeroenDeDauw/GitHub/pull/37, though then I don't see why that would break the extension, so I don't think this fixes this issue here. Unless perhaps the extension was installed twice in different places somehow?

> So this is not helping either.

Did you try the snippet I posted? If so, I assume you held into account there still is the wiki's own page cache.

> I will try to make a new release that logs more shit soon

This is going to have to wait till Friday earliest, very busy ATM

**Comment by kghbln** [comment] 2017-06-14 20:35
> Did you try the snippet I posted? If so, I assume you held into account there still is the wiki's own page cache.

Yes. :(

> This is going to have to wait till Friday earliest, very busy ATM

No worries.

**Comment by JeroenDeDauw** [comment] 2017-06-23 16:33
I've added a new setting that allows disabling the cache via config (https://github.com/JeroenDeDauw/GitHub/pull/38) and also added error logging of failed HTTP requests to GitHub (https://github.com/JeroenDeDauw/GitHub/pull/39). These have not been tested as I do not currently have a working MediaWiki environment, and the later is very dependent on MediaWiki. So someone will need to give this a spin before I release it.

Let's hope some errors do show up in the log so we know what is going on. Else more verbose logging will need to be added.

**Comment by kghbln** [comment] 2017-06-23 16:52
I have created a [gist](https://gist.githubusercontent.com/kghbln/be56111e92f38a136702fcfb9f262bbd/raw/051c07cc8b26d238e68065c7637e0288b1eb14eb/gistfile1.txt) with the logging. I was editing the page "https://www.semantic-mediawiki.org/wiki/Help:API/README" so this is probably there some hopefully useful information pops up.

**Comment by JeroenDeDauw** [comment] 2017-06-23 16:59
Uhm...

> [SpamBlacklist] Old URLs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/api.md
[SpamBlacklist] New URLs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/technical/api.md

**Comment by JeroenDeDauw** [comment] 2017-06-23 17:00
So looks like this issue is caused by the new config you added:

> $egGitHubFetcher = 'mediawiki';

Which causes the extension to go though MediaWiki to get at the file, and MediaWiki is going "nope, not liking this URL" :)

**Comment by kghbln** [comment] 2017-06-23 17:12
> So looks like this issue is caused by the new config you added:

So I added `$egGitHubFetcher = 'mediawiki';` and things are fluffy again. Whitelisting [github](https://www.semantic-mediawiki.org/w/index.php?title=MediaWiki%3ASpam-whitelist&type=revision&diff=51949&oldid=51932) did not change a thing.

Basically you cannot use the `mediawiki` option when the SpamBlacklist extension is installed.

**Comment by JeroenDeDauw** [comment] 2017-06-23 17:13
> So I added

You mean "removed" right?

**Comment by kghbln** [comment] 2017-06-23 17:14
> You mean "removed" right?

There was a typo. Changed to `'simple'` though I could have removed.

**Comment by kghbln** [comment] 2017-06-23 17:15
@JeroenDeDauw 

> Basically you cannot use the mediawiki option when the SpamBlacklist extension is installed.

This should somehow be documented in the extension's README.

**Closed as completed** 2017-06-23 17:16 UTC
Labels: site - s-mw.org - www, server - stetsonia, issue

**Comment by mwjames** [comment] 2017-06-24 14:11
Okay, this is not working as before. Formatting of text marked with \` are no longer correctly attributed [0], something like `Foo` no longer appears as `<code>Foo</code>`. 

[0] https://www.semantic-mediawiki.org/wiki/Help:Integration_tests vs. https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/README.md

**Comment by kghbln** [comment] 2017-06-24 14:13
> Okay, this is not working as before. Formatting of text marked with ` are no longer correctly attributed [0], something like Foo no longer appears as <code>Foo</code>.

Indeed but I believe that this must be addressed by the GitHub extension?!

**Comment by mwjames** [comment] 2017-06-24 14:16
>... be addressed by the GitHub extension?!

https://github.com/JeroenDeDauw/GitHub/issues/42
